### PR TITLE
Add support for locale key injection

### LINKED ISSUE #78: v2 endpoints require modified locale key
### Expected behavior

As per `p77Llu-byF-p2`, v2 endpoints must pass `_locale` rather than `locale`. Prior versions should still use `locale`. 

_From the perspective of semantic versioning, implementing this may be a breaking change._

### Actual behavior

In the [default case](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKit/WordPressComRestApi.swift#L54) where `appendsPreferredLanguageLocale` is `true`, a localization identifier is [added to requests](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKit/WordPressComRestApi.swift#L433-L441) with a key of `locale`. This needs to change based on the endpoint version.

### Steps to reproduce the behavior

Inspect a request constructed via `WordPressKit` and scrutinize the query string. Note the value `locale` is  used for all endpoint versions.

##### WordPressKit Environment
All devices & versions of `WordPressKit`, Xcode & iOS.
 - WordPressKit Version [e.g. 22] : all versions
 - OS: [e.g. iOS 12.1.3 (16D40)] : all versions
 - Device: [e.g. iPhone XS] : all devices
 - Xcode Version: [e.g. Xcode 10.1 (10B61)] : all versions

##### Additional Context
N/A

### PR DESCRIPTION
**Pull request by stevebaranski**
### Description

Fixes #78, which requires that `_locale` be passed as the key to v2 endpoints, while preserving the original `locale` key for prior versions.

This required special consideration, as `ServiceRemoteWordPressComREST` is responsible for endpoint versions, while `WordPressComRestApi` has responsibility for applying locale to requests.

### Testing Details

- Checkout the branch, confirm that it builds, and that both new & existing tests pass.
- Review the code and documentation for additional context.
- From [`WPiOS`](https://github.com/wordpress-mobile/WordPress-iOS/), checkout the branch `try/wpkit-locale-integration` and confirm that it compiles & tests pass. Also launch the app and exercise requests to confirm that there are no regressions.

- [X] Please check here if your pull request includes additional test coverage.

### CODE REVIEW

**Comment by stevebaranski** [comment]
@frosty @SergioEstevao given that this work continues what began in #80, would you two be willing to take a look at this? I'd be especially interested to hear if you have any thoughts on make the change more "strict", or if you think the documentation of this change can be improved in some way.

I've also added @ctarda, as this is potentially relevant to the ongoing work with Site Creation.

Finally, the CircleCI error is due to the fact that this repository is not correctly configured at the moment.

**Comment by SergioEstevao** [comment]
@stevebaranski While you approach in this PR looks ok, I think we are getting on a path that in the future may introduce too much complexity.

I was considering the following alternative, instead of just one WordPressComRestAPI instance ( object not class) what about having two instances:

 - One for the Rest API v1.x
 - Another for the Rest API 2.x

This way we could just set the locale parameter on the constructor of the API object, and we don't need to go around changing depending on the service. If the call is the REST API v2, we get the instance for v2 and make the request.

This way in the future if need to do more changes like this we could even have a different class for API v2.

**Comment by stevebaranski** [comment]
I opted to continue our discussion in the root [issue](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/78). I'd welcome your thoughts.

**Comment by stevebaranski** [comment]
Closing this PR as discussed. I'll open a new one shortly.

**Pull request closed without merging**
