### PR TITLE
Add missing properties to `RemoteGravatarProfile`

### PR DESCRIPTION
**Pull request by ghost**
[WordPress-iOS PR 14654](https://github.com/wordpress-mobile/WordPress-iOS/pull/14654)
For the feature of displaying basic user profile on avatar tap, there were 3 properties which are not being parsed within `RemoteGravatarProfile` initialization:

https://github.com/wordpress-mobile/WordPress-iOS/issues/14609

1- `name.formatted`
2- `currentLocation`
3- `aboutMe`

This PR adds missing properties according to the user profiles techical documentation:
https://wpmobilep2.wordpress.com/2020/08/06/user-profiles-technical-feasibility/

### CODE REVIEW

**Review by Gio2018 — CHANGES_REQUESTED** [review]
Hey @ughuro ! The `podspec` should be updated with the new beta version, thank you!

**Review by Gio2018 — COMMENTED** [review]
The pod spec looks fine now, I'll re-review once the changes to the WPiOS have been made so I'll be able to test both PRs together.
Thank you!!

**Comment by Gio2018** [comment]
Hey @ughuro ! This looks good! Do you mind just updating the version to `4.16-beta.1`? This is because in the meantime, `4.15` was published. Once that is done, I can go ahead and push the beta release, so we can update this accordingly in the `Podfile` of `WordPress-iOS`. Thank you.

**Comment by ughuro** [comment]
Hi @Gio2018, I've updated the version. There's conflict in podspec, but I think you can resolve them? Thank you.

**Comment by Gio2018** [comment]
> Hi @Gio2018, I've updated the version. There's conflict in podspec, but I think you can resolve them? Thank you.

Hey @ughuro , the conflict can be resolved just by setting the correct versioning; since it's part of this pull request, could you please fix it so I can merge a clean one? Thank you!

**Comment by ughuro** [comment]
Hi @Gio2018 , done. 👍

**Review by Gio2018 — APPROVED** [review]

**Pull request merged**
