### PR TITLE
Add endpoints for blogging prompts settings

### PR DESCRIPTION
**Pull request by dvdchr**
Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/18549
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/18695

### Description

This PR adds a new model, `RemoteBloggingPromptsSettings`, to encapsulate the settings data structure for Blogging Prompts. In addition, two methods are added to `BloggingPromptsServiceRemote` to fetch and update the settings. Similar to fetching prompts, these two methods require a site ID.

Additionally, adds `blogging_prompts_settings` to the `RemoteBlog` options helper to prevent it from being dropped from the dictionary when it gets mapped.

### Testing Details

Can be tested with the referenced WPiOS PR.

- [x] Please check here if your pull request includes additional test coverage.
- [x] I have considered updating the `version` in the `.podspec` file.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @dvdchr . You cannot be added as a reviewer I think because you created the PR, so I'm "manually" adding you. 😄 Can you take a look at this please? Thank you!!

**Review by dvdchr — COMMENTED** [review]
LGTM! :shipit: 

(I can't approve my own PR, so @ScoutHarris can you grant us the actual :shipit: ? 😆 )

**Review by ScoutHarris — APPROVED** [review]
David says so. 😄

**Comment by ScoutHarris** [comment]
Thank you @dvdchr ! 🙇

**Comment by wargcm** [comment]
Thanks @ScoutHarris & @dvdchr!

**Pull request merged**
