### PR TITLE
Extend RemotePostService with new create and patch endpoints

### PR DESCRIPTION
**Pull request by kean**
### Description

This PR adds `PostServiceRemoteExtended` with new APIs for creating and patching posts:

```swift
public protocol PostServiceRemoteExtended: PostServiceRemote {
     func createPost(with parameters: RemotePostCreateParameters) async throws -> RemotePost
     func patchPost(withID postID: Int, parameters: RemotePostUpdateParameters) async throws -> RemotePost
 }
```

In the previous implementation, you had to use the response object (`RemotePost`) as an input parameter for updating the posts, which was less than ideal because of the mismatch between the set of available parameters and their format:

```objc
- (void)updatePost:(RemotePost *)post success:(void (^)(RemotePost *post))success failure:(void (^)(NSError *error))failure;
```

The new parameter formats also support creating diffs between two `RemotePostCreateParameters` and applying a diff to `RemotePostCreateParameters`. Both of these features are used by the updated `PostRepository` in WP-iOS.

### Testing Details

See https://github.com/wordpress-mobile/WordPress-iOS/pull/22807

---

- [ ] Please check here if your pull request includes additional test coverage.
- [ ] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by momo-ozawa — APPROVED** [review]
Tested via https://github.com/wordpress-mobile/WordPress-iOS/pull/22807

**Comment by crazytonyli** [comment]
👋 Hi @kean, would you mind adding some unit tests?

**Comment by kean** [comment]
Hey, we have a suite of [integration tests](https://github.com/wordpress-mobile/WordPress-iOS/blob/8083401b4ccb3a56c4a86d87133a5cd1fc0fddb5/WordPress/WordPressTest/PostRepositorySaveTests.swift) in the [following PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/22807). It has complete coverage for this change, including the `underlyingError` addition, diff, and both the new methods.

**Comment by crazytonyli** [comment]
They are in a separate repository though. It'd be nice to have complete coverage on these changes in this repo here too.

**Pull request merged**
